# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from time import sleep
from os import path
from pytest import mark


class TestAddstudentcoursedisciplineandsubscribe:
    def setup_method(self, method):
        ROOT_DIR = path.dirname(path.abspath(__file__))
        self.driver = webdriver.Chrome(executable_path=f"{ROOT_DIR}/chromedriver")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    @mark.skip(reason="Skiping due git actions")
    def test_addstudentcoursedisciplineandsubscribe(self):
        self.driver.get("http://127.0.0.1:5000")
        self.driver.set_window_size(623, 783)
        sleep(10)
        self.driver.find_element(By.ID, "student-name").click()
        self.driver.find_element(By.ID, "student-name").send_keys("Douglas")
        self.driver.find_element(By.ID, "student-btn").click()
        element = self.driver.find_element(By.ID, "student-btn")
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        self.driver.find_element(By.ID, "course-name").click()
        self.driver.find_element(By.ID, "course-name").send_keys("Eng")
        self.driver.find_element(By.ID, "course-btn").click()
        element = self.driver.find_element(By.ID, "course-btn")
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        self.driver.find_element(By.ID, "course-name").click()
        self.driver.find_element(By.ID, "course-name").click()
        element = self.driver.find_element(By.ID, "course-name")
        self.driver.find_element(By.ID, "course-name").send_keys("Med")
        self.driver.find_element(By.ID, "course-btn").click()
        element = self.driver.find_element(By.ID, "course-btn")
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        self.driver.find_element(By.ID, "course-name").click()
        self.driver.find_element(By.ID, "course-name").send_keys("Adm")
        self.driver.find_element(By.ID, "course-btn").click()
        element = self.driver.find_element(By.ID, "course-btn")
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        self.driver.find_element(By.ID, "student-id").click()
        self.driver.find_element(By.ID, "student-id").send_keys("1")
        self.driver.find_element(By.ID, "course-id").click()
        self.driver.find_element(By.ID, "course-id").send_keys("1")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(4) > #course-btn"
        ).click()
        self.driver.find_element(By.ID, "discipline-name").click()
        self.driver.find_element(By.ID, "discipline-name").send_keys("Math")
        self.driver.find_element(By.ID, "course-discipline-id").click()
        self.driver.find_element(By.ID, "course-discipline-id").send_keys("1")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn"
        ).click()
        element = self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn"
        )
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        self.driver.find_element(By.ID, "discipline-name").click()
        self.driver.find_element(By.ID, "discipline-name").click()
        element = self.driver.find_element(By.ID, "discipline-name")
        self.driver.find_element(By.ID, "discipline-name").send_keys("Calc")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn"
        ).click()
        element = self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn"
        )
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        self.driver.find_element(By.ID, "discipline-name").click()
        self.driver.find_element(By.ID, "discipline-name").click()
        element = self.driver.find_element(By.ID, "discipline-name")
        self.driver.find_element(By.ID, "discipline-name").send_keys("Topology")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(5) > #course-btn"
        ).click()
        self.driver.find_element(By.ID, "subscribe-student-id").click()
        self.driver.find_element(By.ID, "subscribe-student-id").send_keys("1")
        self.driver.find_element(By.ID, "subscribe-discipline-id").click()
        self.driver.find_element(By.ID, "subscribe-discipline-id").send_keys("1")
        self.driver.find_element(
            By.CSS_SELECTOR, ".form-group:nth-child(6) > #course-btn"
        ).click()
