apiVersion: v1
kind: Service
metadata: # ObjectMeta
    name: tdd-detroid
spec: # ServiceSpec
  selector:
    app: tdd-detroid
  ports:
    - port: 5000
      name: tdd-detroid
      targetPort: detroid-port
      nodePort: 30500
    - port: 3000
      name: postgrest
      nodePort: 30501
    - port: 5432
      name: postgres
      nodePort: 30502
  type: NodePort