apiVersion: v1
kind: Service
metadata: # ObjectMeta
    name: tdd-detroid
spec: # ServiceSpec
  selector:
    app: tdd-detroid
  ports:
    - port: 5000
      name: tdd-detroid
    - port: 3000
      name: postgrest
    - port: 5432
      name: postgres
  type: NodePort