MINIMUM_STUDENTS_IN_COURSE = 9
MAXIMUM_STUDENTS_IN_COURSE = 900

MAXIMUM_SUBJECTS_IN_TEACHER = 3

MINIMUN_SUBJECTS_IN_COURSE = 3
MAXIMUM_SUBJECTS_IN_COURSE = 30

MINIMUM_STUDENT_GRADE = 7
MINIMUN_SUBJECTS_IN_STUDENT = 3
